version: "3.3"

services:
  unifi-controller:
    image: linuxserver/unifi-controller:arm32v7-latest
    container_name: unifi-controller
    hostname: unifi-controller
    networks:
      - traefiknet
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
    volumes:
      - ./data:/config
    ports:
      - 3478:3478/udp   # STUN
      - 10001:10001/udp # port for device discovery
      - 8080:8080       # device communication
      #- 8081:8081
      #- 8443:8443       # gui in browser for testing
      #- 8843:8843
      #- 8880:8880
      - 6789:6789       # speed test
    restart: always
    expose:
      - 8443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.rule=Host(`${URL0_SAN}`)"
      - "traefik.http.routers.unifi.entrypoints=websecure"
      #- "traefik.http.routers.unifi.service=unifi@docker"
      - "traefik.http.routers.unifi.tls=true"
      - "traefik.http.routers.unifi.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.unifi.middlewares=unifiproxy"
      
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.passhostheader=true"

      #- "traefik.http.middlewares.unifiproxy.headers.accesscontrolallowcredentials=true"
      #- "traefik.http.middlewares.unifiproxy.headers.accesscontrolexposeheaders=Access-Control-Allow-Origin,Access-Control-Allow-Credentials"
      #- "traefik.http.middlewares.unifiproxy.headers.addvaryheader=true"
      - "traefik.http.middlewares.unifiproxy.headers.framedeny=true"
      - "traefik.http.middlewares.unifiproxy.headers.sslredirect=true"
      - "traefik.http.middlewares.unifiproxy.headers.browserxssfilter=true"
      #- "traefik.http.middlewares.unifiproxy.headers.sslhost=${URL0_SAN}"
      - "traefik.http.middlewares.unifiproxy.headers.stsseconds=315360000"
      - "traefik.http.middlewares.unifiproxy.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.unifiproxy.headers.stspreload=true"
      - "traefik.http.middlewares.unifiproxy.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.unifiproxy.headers.sslforcehost=true"

networks:
    traefiknet:
        external: true