version: "3.3"

services:
    clair: 
        image: quay.io/coreos/clair:v2.1.2
        container_name: clair
        volumes:
            - ./config.yaml:/config/config.yaml
        networks:
            - traefik
        envioronment:
            - POSTGRES_PASSWORD=${DB_PASS}
  
    postgres:
      image: postgres
      volumes:
        - cldb:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_DB: clair

networks:
  traefik:
    external: true

volumes:
  cldb: